/**
 * Created by zhangran on 16/10/2.
 */

export default {
  group: {
    CLEAR: 'CLEAR',
    START_ADD: 'START_ADD',
    ADD_SUCCESS: 'ADD_SUCCESS',
    ADD_FAILED: 'ADD_FAILED',
    GET_LIST_SUCCESS: 'GET_LIST_SUCCESS',
    GET_DETAIL_SUCCESS: 'GET_DETAIL_SUCCESS',
    SAVE_DETAIL_SUCCESS: 'SAVE_DETAIL_SUCCESS'
  },
  user: {
    CLEAR: 'CLEAR',
    START_ADD: 'START_ADD',
    ADD_SUCCESS: 'ADD_SUCCESS',
    ADD_FAILED: 'ADD_FAILED',
    GET_LIST_SUCCESS: 'GET_LIST_SUCCESS',
    GET_DETAIL_SUCCESS: 'GET_DETAIL_SUCCESS',
    SAVE_DETAIL_SUCCESS: 'SAVE_DETAIL_SUCCESS'
  }
}
