/**
 * Created by zhangran on 16/10/2.
 */

export default {
  group: {
    CLEAR: 'CLEAR_GROUP',
    START_ADD: 'START_ADD_GROUP',
    ADD_SUCCESS: 'ADD_GROUP_SUCCESS',
    ADD_FAILED: 'ADD_GROUP_FAILED',
    GET_LIST_SUCCESS: 'GET_GROUP_LIST_SUCCESS',
    GET_DETAIL_SUCCESS: 'GET_GROUP_DETAIL_SUCCESS',
    SAVE_DETAIL_SUCCESS: 'SAVE_GROUP_DETAIL_SUCCESS'
  },
  user: {
    CLEAR: 'CLEAR_USER',
    START_ADD: 'START_ADD_USER',
    ADD_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_FAILED: 'ADD_USER_FAILED',
    GET_LIST_SUCCESS: 'GET_USER_LIST_SUCCESS',
    GET_DETAIL_SUCCESS: 'GET_USER_DETAIL_SUCCESS',
    SAVE_DETAIL_SUCCESS: 'SAVE_USER_DETAIL_SUCCESS'
  },
  login: {
    CLEAR: 'CLEAR_LOGIN',
    START: 'START_LOGIN',
    SUCCESS: 'LOGIN_SUCCESS',
    FAIL: 'LOGIN_FAIL'
  }
}
